-- Comprobar si la base de datos existe y eliminarla si es necesario
IF DB_ID(N'BD_CLIENTES') IS NOT NULL
    DROP DATABASE BD_CLIENTES
GO

-- Crear la base de datos BD_CLIENTES
CREATE DATABASE BD_CLIENTES ON
  PRIMARY (
  NAME = N'BD_CLIENTES',
  FILENAME = N'/var/opt/mssql/data/BD_CLIENTES.mdf',
  SIZE = 50MB,
  FILEGROWTH = 10MB
)
LOG ON (
  NAME = N'BD_CLIENTES_log',
  FILENAME = N'/var/opt/mssql/data/BD_CLIENTES_log.ldf',
  SIZE = 10MB,
  FILEGROWTH = 5MB
)
GO

-- Usar la base de datos BD_CLIENTES
USE BD_CLIENTES
GO

-- Crear la tabla CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE INT IDENTITY NOT NULL CONSTRAINT PK_CLIENTES PRIMARY KEY,
    NOM_CLIENTE VARCHAR(100) NOT NULL,
    APE_PATERNO VARCHAR(100) NOT NULL,
    APE_MATERNO VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    GENERO VARCHAR(20)
)
GO

-- Crear la tabla TIPOS_DOCUMENTOS
CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOCUMENTO TINYINT IDENTITY NOT NULL CONSTRAINT PK_TIPOS_DOCUMENTOS PRIMARY KEY,
    ID_CLI INT NOT NULL,
    DES_TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
    NUM_DOCUMENTO INT NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    IMAGEN IMAGE NULL,
    CONSTRAINT FK_TIPOS_DOCUMENTOS_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Crear la tabla TIPO_CORREO
CREATE TABLE TIPO_CORREO (
    ID_TIPO_CORREO TINYINT IDENTITY NOT NULL CONSTRAINT PK_TIPO_CORREO PRIMARY KEY,
    ID_CLI INT NOT NULL,
    TIPO_CORREO VARCHAR(40) NOT NULL,
    DES_TIPO_CORREO NVARCHAR(200) NOT NULL,
    CONSTRAINT FK_TIPO_CORREO_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Crear la tabla TIPO_DIRECCION
CREATE TABLE TIPO_DIRECCION (
    ID_DIRECCION TINYINT IDENTITY NOT NULL CONSTRAINT PK_TIPO_DIRECCION PRIMARY KEY,
    ID_CLI INT NOT NULL,
    TIPO_DIRECCION VARCHAR(40) NOT NULL,
    DES_TIPO_DIRECCION NVARCHAR(200) NOT NULL,
    CALLE NVARCHAR(50) NOT NULL,
    REFERENCIA TEXT,
    CONSTRAINT FK_TIPO_DIRECCION_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Crear la tabla TIPO_SEGURO
CREATE TABLE TIPO_SEGURO (
    ID_SEGURO TINYINT IDENTITY NOT NULL CONSTRAINT PK_TIPO_SEGURO PRIMARY KEY,
    ID_CLI INT NOT NULL,
    TIP_SEGURO NVARCHAR(40) NOT NULL,
    POLIZA NVARCHAR(30) NOT NULL,
    COBERTURA DECIMAL(18, 2) NOT NULL, -- Corregido el tipo de dato
    DOCUMENTO_SEGURO IMAGE,
    CONSTRAINT FK_TIPO_SEGURO_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Crear la tabla TIPO_RESIDENCIA
CREATE TABLE TIPO_RESIDENCIA (
    ID_RESIDENCIA TINYINT IDENTITY NOT NULL CONSTRAINT PK_TIPO_RESIDENCIA PRIMARY KEY,
    ID_CLI INT NOT NULL,
    DES_TIP_RESI NVARCHAR(30) NOT NULL,
    PAIS NVARCHAR(50) NOT NULL,
    CIUDAD NVARCHAR(50) NOT NULL,
    PROVINCIA NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_TIPO_RESIDENCIA_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Crear la tabla CLIENTE_DETALLE
CREATE TABLE CLIENTE_DETALLE (
    ID_CLI_DET TINYINT IDENTITY NOT NULL CONSTRAINT PK_CLI_DETALLE PRIMARY KEY,
    ID_CLI INT NOT NULL,
    CORREO NVARCHAR(200) NOT NULL,
    SEGURO VARCHAR(40) NOT NULL,
    DIRECCION NVARCHAR(200) NOT NULL,
    DOCUMENTO INT NOT NULL,
    RESIDENCIA NVARCHAR(200) NOT NULL,
    CONSTRAINT FK_CLIENTE_DETALLE_CLIENTES FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

-- Insertar datos en la tabla CLIENTES
INSERT INTO CLIENTES (NOM_CLIENTE, APE_PATERNO, APE_MATERNO, NUMERO, GENERO)
VALUES
    ('Josue', 'Chambilla', 'Zuñiga', 69696969, 'Masculino'),
    ('Jean', 'Valverde', 'Zamora', 12345678, 'Masculino')
GO

-- Insertar datos en la tabla CLIENTE_DETALLE
INSERT INTO CLIENTE_DETALLE (ID_CLI, CORREO, SEGURO, DIRECCION, DOCUMENTO, RESIDENCIA)
VALUES
    (1, 'josue.200297@virtual.upt', '485691', 'AV. Los Molinos', 69696969, 'Tacna - Peru'),
    (2, 'Jean.200297@virtual.upt', '365874', 'AV. Los Cals', 12345678, 'Tacna - Peru')
GO

-- Insertar datos en la tabla TIPO_CORREO
INSERT INTO TIPO_CORREO (ID_CLI, TIPO_CORREO, DES_TIPO_CORREO)
VALUES
    (1, 'Personal', 'josue.200297@virtual.upt'),
    (2, 'Personal', 'jean.2020297@virtual.upt')
GO

-- Insertar datos en la tabla TIPO_DIRECCION
INSERT INTO TIPO_DIRECCION (ID_CLI, TIPO_DIRECCION, DES_TIPO_DIRECCION, CALLE, REFERENCIA)
VALUES
    (1, 'Personal', 'Zona A', 'AV. Los Molinos', '6 cuadras mas arriba de Palca'),
    (2, 'Personal', 'Zona B', 'AV. Los Cals', '6 cuadras mas arriba de Toms')
GO

-- Insertar datos en la tabla TIPO_RESIDENCIA
INSERT INTO TIPO_RESIDENCIA (ID_CLI, DES_TIP_RESI, PAIS, CIUDAD, PROVINCIA)
VALUES
    (1, 'Permanente', 'Peru', 'Tacna', 'Tacna'),
    (2, 'Temporal', 'Peru', 'Tacna', 'Tacna')
GO

-- Insertar datos en la tabla TIPO_SEGURO
INSERT INTO TIPO_SEGURO (ID_CLI, TIP_SEGURO, POLIZA, COBERTURA, DOCUMENTO_SEGURO)
VALUES
    (1, 'Equipaje', '123546', 25.00, NULL),
    (2, 'Salud', '200000', 235.12, NULL)
GO

-- Insertar datos en la tabla TIPOS_DOCUMENTOS
INSERT INTO TIPOS_DOCUMENTOS (ID_CLI, DES_TIPO_DOCUMENTO, NUM_DOCUMENTO, FECHA_EMISION, FECHA_VENCIMIENTO, IMAGEN)
VALUES
    (1, 'Pasaporte', 54124512, '2023-08-11', '2029-12-09', NULL),
    (2, 'DNI', 32132123, '2023-05-24', '2100-12-22', NULL)
GO
